services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel-shopify-app.local
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./../DB8_NOPASS:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "backend/laravel-shopify-app"
    ports:
      - 8000:8000
    user: 1000:1000
    entrypoint: php artisan serve --host=0.0.0.0
    environment:
      - COMPOSER_HOME=/tmp
    volumes:
      - ./backend:/var/www/backend
      - ./backend/vendor:/var/www/backend/vendor
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 5173:5173
    entrypoint: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/var/www/frontend
      - ./frontend/node_modules:/var/www/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./.docker/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    environment:
      - proxy_no_cache=1
      - proxy_cache_bypass=1
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
      - "8080"
      - "5173"
    depends_on:
      - backend
      - nginx-proxy
    links:
      - backend
    environment:
      - VIRTUAL_HOST=laravel-shopify-app.local
      - VIRTUAL_PORT=80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
